In [33]:
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

# basic

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.full((2,3), np.pi)

array([[3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265]])

In [19]:
np.empty((2,3))

array([[3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265]])

In [8]:
arr = np.zeros((3,4))
print("shape : {}".format(arr.shape))
print("ndim : {}".format(arr.ndim))
print("size : {}".format(arr.size))

shape : (3, 4)
ndim : 2
size : 12


In [20]:
np.array([[1,2,3,4], [10, 20, 30, 40]])

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

In [21]:
np.arange(1, 5)

array([1, 2, 3, 4])

In [22]:
np.arange(1, 5, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

# evenly interval

In [25]:
np.linspace(0, 10, 7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

# random

In [29]:
uniform_distribution = np.random.rand(3,4)
print(uniform_distribution)

[[0.56593426 0.63156816 0.75627337 0.1104527 ]
 [0.46706701 0.64945446 0.92840347 0.07618512]
 [0.69863981 0.64022512 0.11331499 0.21156042]]


In [31]:
normal_distribution = np.random.randn(3,4)
print(normal_distribution)

[[-1.52017141  1.70645769 -1.37966405 -0.73896096]
 [-0.32687386  0.60913989  0.45669607 -1.37237842]
 [-0.03200638  0.61725888 -0.19916274  1.51369617]]


# customer array generator function

In [52]:
def array_generator_function(z, y, x):
    return z

np.fromfunction(array_generator_function, (2, 2, 2))

array([[[0., 0.],
        [0., 0.]],

       [[1., 1.],
        [1., 1.]]])

# data type

In [55]:
arr = np.ones((3,4))
arr.dtype

dtype('float64')

In [56]:
arr = np.ones((3,4))
arr.itemsize

8

# reshape

In [58]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [60]:
arr.shape = (3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [62]:
arr_reshape = arr.reshape(2, 6)
arr_reshape

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [66]:
arr_ravel = arr.ravel()
arr_ravel

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# conditional operators

In [69]:
arr = np.array([0, 1, 2, 3])
arr < 2

array([ True,  True, False, False])

In [70]:
arr[arr < 2]

array([0, 1])

# statistical  function

In [74]:
arr = np.arange(12).reshape(3, 4)
print(arr)
print("min : {}".format(arr.min(axis=0)))
print("max : {}".format(arr.max(axis=0)))
print("sum : {}".format(arr.sum(axis=0)))
print("prod : {}".format(arr.prod(axis=0)))
print("std : {}".format(arr.std(axis=0)))
print("var : {}".format(arr.var(axis=0)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
min : [0 1 2 3]
max : [ 8  9 10 11]
sum : [12 15 18 21]
prod : [  0  45 120 231]
std : [3.26598632 3.26598632 3.26598632 3.26598632]
var : [10.66666667 10.66666667 10.66666667 10.66666667]


# universal function

In [82]:
arr = np.arange(12).reshape(3, 4)
print(arr)
print("abs : \n{}".format(np.abs(arr)))
print("sqrt : \n{}".format(np.sqrt(arr)))
print("exp : \n{}".format(np.exp(arr)))
print("log : \n{}".format(np.log(arr)))
print("sign : \n{}".format(np.sign(arr)))
print("ceil : \n{}".format(np.ceil(arr)))
print("modf : \n{}".format(np.modf(arr)))
print("isnan : \n{}".format(np.isnan(arr)))
print("cos : \n{}".format(np.cos(arr)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
abs : 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
sqrt : 
[[0.         1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974 2.64575131]
 [2.82842712 3.         3.16227766 3.31662479]]
exp : 
[[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03]
 [2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04]]
log : 
[[      -inf 0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947 1.94591015]
 [2.07944154 2.19722458 2.30258509 2.39789527]]
sign : 
[[0 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
ceil : 
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
modf : 
(array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]]), array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]]))
isnan : 
[[False False False False]
 [False False False False]
 [False False False False]]
cos : 
[[ 1.          0.5403023

/home/hsiehpinghan/anaconda3/envs/python3.6/lib/python3.6/site-packages/ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in log
  


# binary universal function

In [85]:
arr_0 = np.array([0, 1, 2, 3])
arr_1 = np.array([-2, -1, 0, 1])
print("arr_0 : {}".format(arr_0))
print("arr_1 : {}".format(arr_1))
print("add : {}".format(np.add(arr_0, arr_1)))
print("greater : {}".format(np.greater(arr_0, arr_1)))
print("maximum : {}".format(np.maximum(arr_0, arr_1)))
print("copysign : {}".format(np.copysign(arr_0, arr_1)))

arr_0 : [0 1 2 3]
arr_1 : [-2 -1  0  1]
add : [-2  0  2  4]
greater : [ True  True  True  True]
maximum : [0 1 2 3]
copysign : [-0. -1.  2.  3.]


# one dimensional array indexing

In [87]:
arr = np.array([0, 1, 2, 3])
arr

array([0, 1, 2, 3])

In [90]:
arr[1]

1

In [92]:
arr[1:3]

array([1, 2])

In [93]:
arr[1:-1]

array([1, 2])

In [94]:
arr[1::2]

array([1, 3])

In [96]:
arr[::-1]

array([3, 2, 1, 0])

# multi dimensionals array indexing

In [122]:
arr = np.arange(12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [106]:
arr[1, 2]

6

In [124]:
arr[1, ]

array([4, 5, 6, 7])

In [107]:
arr[1:3, ]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# fancy indexing

In [108]:
arr = np.arange(12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [111]:
arr[(0, 2), ]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [112]:
arr[(0, 2), 1:3]

array([[ 1,  2],
       [ 9, 10]])

In [113]:
arr[(0, 2), (1, 3)]

array([ 1, 11])

# copy

In [97]:
arr = np.array([0, 1, 2, 3])
arr[1:3].copy()

array([1, 2])

# boolean indexing

In [125]:
arr = np.arange(12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [126]:
arr[[True, False, True],]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [128]:
arr[:,[True, False, True, False]]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

# select axis by sequence

In [135]:
arr = np.arange(12).reshape(3, 4)
print(arr)
arr[np.ix_([0, 2], [1, 3])]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 1,  3],
       [ 9, 11]])