In [1]:
import numpy as np

# basic

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [4]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
np.full((2,3), np.pi)

array([[3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265]])

In [6]:
np.empty((2,3))

array([[3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265]])

In [7]:
arr = np.zeros((3,4))
print("shape : {}".format(arr.shape))
print("ndim : {}".format(arr.ndim))
print("size : {}".format(arr.size))

shape : (3, 4)
ndim : 2
size : 12


In [8]:
np.array([[1,2,3,4], [10, 20, 30, 40]])

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

In [9]:
np.arange(1, 5)

array([1, 2, 3, 4])

In [10]:
np.arange(1, 5, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

# evenly interval

In [11]:
np.linspace(0, 10, 7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

# random

In [12]:
uniform_distribution = np.random.rand(3,4)
print(uniform_distribution)

[[0.06199383 0.3625925  0.65248424 0.53291378]
 [0.92147681 0.07305948 0.11941908 0.83655022]
 [0.28443175 0.60098105 0.7868902  0.30273532]]


In [13]:
normal_distribution = np.random.randn(3,4)
print(normal_distribution)

[[-0.10975817 -0.17908989 -0.69300288 -2.37048141]
 [-0.71331195  0.15450808  1.06125751  0.23545424]
 [-0.68292542 -0.92662089  1.83768755  3.05196217]]


# customer array generator function

In [14]:
def array_generator_function(z, y, x):
    return z

np.fromfunction(array_generator_function, (2, 2, 2))

array([[[0., 0.],
        [0., 0.]],

       [[1., 1.],
        [1., 1.]]])

# data type

In [15]:
arr = np.ones((3,4))
arr.dtype

dtype('float64')

In [16]:
arr = np.ones((3,4))
arr.itemsize

8

# reshape

In [17]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
arr.shape = (3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
arr_reshape = arr.reshape(2, 6)
arr_reshape

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [20]:
arr_ravel = arr.ravel()
arr_ravel

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# conditional operators

In [21]:
arr = np.array([0, 1, 2, 3])
arr < 2

array([ True,  True, False, False])

In [22]:
arr[arr < 2]

array([0, 1])

# statistical  function

In [23]:
arr = np.arange(12).reshape(3, 4)
print(arr)
print("min : {}".format(arr.min(axis=0)))
print("max : {}".format(arr.max(axis=0)))
print("sum : {}".format(arr.sum(axis=0)))
print("prod : {}".format(arr.prod(axis=0)))
print("std : {}".format(arr.std(axis=0)))
print("var : {}".format(arr.var(axis=0)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
min : [0 1 2 3]
max : [ 8  9 10 11]
sum : [12 15 18 21]
prod : [  0  45 120 231]
std : [3.26598632 3.26598632 3.26598632 3.26598632]
var : [10.66666667 10.66666667 10.66666667 10.66666667]


# universal function

In [24]:
arr = np.arange(12).reshape(3, 4)
print(arr)
print("abs : \n{}".format(np.abs(arr)))
print("sqrt : \n{}".format(np.sqrt(arr)))
print("exp : \n{}".format(np.exp(arr)))
print("log : \n{}".format(np.log(arr)))
print("sign : \n{}".format(np.sign(arr)))
print("ceil : \n{}".format(np.ceil(arr)))
print("modf : \n{}".format(np.modf(arr)))
print("isnan : \n{}".format(np.isnan(arr)))
print("cos : \n{}".format(np.cos(arr)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
abs : 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
sqrt : 
[[0.         1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974 2.64575131]
 [2.82842712 3.         3.16227766 3.31662479]]
exp : 
[[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03]
 [2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04]]
log : 
[[      -inf 0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947 1.94591015]
 [2.07944154 2.19722458 2.30258509 2.39789527]]
sign : 
[[0 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
ceil : 
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
modf : 
(array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]]), array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]]))
isnan : 
[[False False False False]
 [False False False False]
 [False False False False]]
cos : 
[[ 1.          0.5403023

/home/hsiehpinghan/anaconda3/envs/python3.6/lib/python3.6/site-packages/ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in log
  


# binary universal function

In [25]:
arr_0 = np.array([0, 1, 2, 3])
arr_1 = np.array([-2, -1, 0, 1])
print("arr_0 : {}".format(arr_0))
print("arr_1 : {}".format(arr_1))
print("add : {}".format(np.add(arr_0, arr_1)))
print("greater : {}".format(np.greater(arr_0, arr_1)))
print("maximum : {}".format(np.maximum(arr_0, arr_1)))
print("copysign : {}".format(np.copysign(arr_0, arr_1)))

arr_0 : [0 1 2 3]
arr_1 : [-2 -1  0  1]
add : [-2  0  2  4]
greater : [ True  True  True  True]
maximum : [0 1 2 3]
copysign : [-0. -1.  2.  3.]


# one dimensional array indexing

In [26]:
arr = np.array([0, 1, 2, 3])
arr

array([0, 1, 2, 3])

In [27]:
arr[1]

1

In [28]:
arr[1:3]

array([1, 2])

In [29]:
arr[1:-1]

array([1, 2])

In [30]:
arr[1::2]

array([1, 3])

In [31]:
arr[::-1]

array([3, 2, 1, 0])

# multi dimensionals array indexing

In [32]:
arr = np.arange(12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
arr[1, 2]

6

In [34]:
arr[1, ]

array([4, 5, 6, 7])

In [35]:
arr[1:3, ]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# fancy indexing

In [36]:
arr = np.arange(12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
arr[(0, 2), ]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [38]:
arr[(0, 2), 1:3]

array([[ 1,  2],
       [ 9, 10]])

In [39]:
arr[(0, 2), (1, 3)]

array([ 1, 11])

# copy

In [40]:
arr = np.array([0, 1, 2, 3])
arr[1:3].copy()

array([1, 2])

# boolean indexing

In [41]:
arr = np.arange(12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
arr[[True, False, True],]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [43]:
arr[:,[True, False, True, False]]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

# select axis by sequence

In [44]:
arr = np.arange(12).reshape(3, 4)
print(arr)
arr[np.ix_([0, 2], [1, 3])]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 1,  3],
       [ 9, 11]])

# Iterating

In [45]:
arr = np.arange(24).reshape(2, 3, 4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [46]:
for matrix in arr:
    print(matrix)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [47]:
for i in range(len(arr)):
    print(arr[i])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [48]:
for i in arr.flat:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


# stacking array

In [49]:
arr_0 = np.full((3,4), 0.0)
arr_0

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [50]:
arr_1 = np.full((3,4), 1.0)
arr_1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [51]:
arr_2 = np.full((3,4), 2.0)
arr_2

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [52]:
np.vstack((arr_0, arr_1, arr_2))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [53]:
np.hstack((arr_0, arr_1, arr_2))

array([[0., 0., 0., 0., 1., 1., 1., 1., 2., 2., 2., 2.],
       [0., 0., 0., 0., 1., 1., 1., 1., 2., 2., 2., 2.],
       [0., 0., 0., 0., 1., 1., 1., 1., 2., 2., 2., 2.]])

In [54]:
np.concatenate((arr_0, arr_1, arr_2), axis=0)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [55]:
np.concatenate((arr_0, arr_1, arr_2), axis=1)

array([[0., 0., 0., 0., 1., 1., 1., 1., 2., 2., 2., 2.],
       [0., 0., 0., 0., 1., 1., 1., 1., 2., 2., 2., 2.],
       [0., 0., 0., 0., 1., 1., 1., 1., 2., 2., 2., 2.]])

In [56]:
np.stack((arr_0, arr_1, arr_2))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]]])

# splitting array

In [57]:
arr = np.arange(24).reshape(6,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [58]:
arr_0, arr_1 = np.vsplit(arr, 2)
print(arr_0)
print(arr_1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [59]:
arr_0, arr_1 = np.hsplit(arr, 2)
print(arr_0)
print(arr_1)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]
 [16 17]
 [20 21]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]
 [18 19]
 [22 23]]


# transposing array

In [60]:
arr = np.arange(12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [61]:
arr.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [62]:
arr.transpose((1, 0))

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [63]:
arr.swapaxes(0,1)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [64]:
arr.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])