In [1]:
import numpy as np
import numpy.linalg as linalg

# mesh grid

In [2]:
x_coords = np.arange(0, 3)
y_coords = np.arange(0, 2)
X, Y = np.meshgrid(x_coords, y_coords)

In [3]:
X

array([[0, 1, 2],
       [0, 1, 2]])

In [4]:
Y

array([[0, 0, 0],
       [1, 1, 1]])

In [5]:
X*Y

array([[0, 0, 0],
       [0, 1, 2]])

# solving linear scalar equation

    2x + 6y = 6
    5x + 3y = -9

In [6]:
coeffs  = np.array([[2, 6], [5, 3]])
depvars = np.array([6, -9])
solution = linalg.solve(coeffs, depvars)
solution

array([-3.,  2.])

In [7]:
np.allclose(coeffs.dot(solution), depvars)

True