In [1]:
import numpy as np

# binary .npy format

In [2]:
arr = np.arange(12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
np.save("/tmp/binary", arr)
loaded_arr = np.load("/tmp/binary.npy")
loaded_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# text format

In [4]:
arr = np.arange(12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
np.savetxt("/tmp/text.csv", arr)
loaded_arr = np.loadtxt("/tmp/text.csv")
loaded_arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

# zipped .npz format

In [6]:
arr_0 = np.arange(12).reshape(3, 4)
arr_0

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
arr_1 = np.arange(6).reshape(2, 3)
arr_1

array([[0, 1, 2],
       [3, 4, 5]])

In [8]:
np.savez("/tmp/zip", arr_0 = arr_0, arr_1 = arr_1)
loaded_object = np.load("/tmp/zip.npz")
loaded_object.keys()

['arr_0', 'arr_1']

In [9]:
loaded_object["arr_0"]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
loaded_object["arr_1"]

array([[0, 1, 2],
       [3, 4, 5]])