In [1]:
import numpy as np
import numpy.linalg as linalg

# dot product

In [2]:
arr_0 = np.arange(4).reshape(2,2)
print(arr_0)
print()
arr_1 = np.arange(6).reshape(2,3)
print(arr_1)
arr_0.dot(arr_1)

[[0 1]
 [2 3]]

[[0 1 2]
 [3 4 5]]


array([[ 3,  4,  5],
       [ 9, 14, 19]])

# inverse and pseudo-inverse

In [3]:
arr = np.arange(4).reshape(2,2)
linalg.inv(arr)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [4]:
arr = np.arange(4).reshape(2,2)
linalg.pinv(arr)

array([[-1.50000000e+00,  5.00000000e-01],
       [ 1.00000000e+00,  5.55111512e-17]])

In [5]:
arr.dot(linalg.inv(arr)) # arr * arr' equals identity matrix

array([[1., 0.],
       [0., 1.]])

# QR decomposition

In [6]:
arr = np.arange(9).reshape(3, 3)
q, r = linalg.qr(arr)
print(q)
print()
print(r)

[[ 0.          0.91287093  0.40824829]
 [-0.4472136   0.36514837 -0.81649658]
 [-0.89442719 -0.18257419  0.40824829]]

[[-6.70820393e+00 -8.04984472e+00 -9.39148551e+00]
 [ 0.00000000e+00  1.09544512e+00  2.19089023e+00]
 [ 0.00000000e+00  0.00000000e+00 -3.65307819e-16]]


In [7]:
q.dot(r)  # q.r equals arr

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

# determinant

In [8]:
arr = np.arange(4).reshape(2, 2)
linalg.det(arr)

-2.0

# eigenvalue and eigenvector

In [9]:
arr = np.arange(4).reshape(2, 2)
eigenvalue, eigenvector = linalg.eig(arr)
print(eigenvalue)
print()
print(eigenvector)

[-0.56155281  3.56155281]

[[-0.87192821 -0.27032301]
 [ 0.48963374 -0.96276969]]


In [10]:
arr.dot(eigenvector) - eigenvalue * eigenvector  # arr.v - λ*v = 0

array([[ 0.00000000e+00,  0.00000000e+00],
       [ 1.66533454e-16, -4.44089210e-16]])

# singular value decomposition

In [11]:
arr = np.array([[1,0,0,0,2], [0,0,3,0,0], [0,0,0,0,0], [0,2,0,0,0]])
arr

array([[1, 0, 0, 0, 2],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0]])

In [12]:
U, S_diag, V = linalg.svd(arr)

In [13]:
U

array([[ 0.,  1.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -1.],
       [ 0.,  0.,  1.,  0.]])

In [14]:
S = np.zeros((4, 5))
S[np.diag_indices(4)] = S_diag
S  # Σ

array([[3.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 2.23606798, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 2.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])

In [15]:
V

array([[-0.        ,  0.        ,  1.        ,  0.        ,  0.        ],
       [ 0.4472136 ,  0.        ,  0.        ,  0.        ,  0.89442719],
       [-0.        ,  1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ,  0.        ],
       [-0.89442719,  0.        ,  0.        ,  0.        ,  0.4472136 ]])

In [16]:
U.dot(S).dot(V) # U.Σ.V == arr

array([[1., 0., 0., 0., 2.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.]])

# diagonal and trace

In [17]:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
np.diag(arr)

array([0, 4, 8])

In [19]:
np.trace(arr)  # equivalent to np.diag(arr).sum()

12

# solving linear scalar equation

    2x + 6y = 6
    5x + 3y = -9

In [20]:
coeffs  = np.array([[2, 6], [5, 3]])
depvars = np.array([6, -9])
solution = linalg.solve(coeffs, depvars)
solution

array([-3.,  2.])

In [21]:
np.allclose(coeffs.dot(solution), depvars)

True